# SPDX-FileCopyrightText:  ANNO DOMINI 2024  Jan Chren ~rindeal  <dev.rindeal gmail com>
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only

name: "{{ ACTION_NAME }}"
description: "{{ ACTION_DESCRIPTION }}"
author: Jan Chren ~rindeal
branding:  # https://haya14busa.github.io/github-action-brandings/
  icon:    # https://feathericons.com/
  color:   # one of: white, yellow, blue, green, orange, red, purple, grey-dark

# The `inputs` and `outputs` IDs must match ^[a-zA-Z_][a-zA-Z0-9_-]*$
inputs:
  'my-custom-input-string':
    description: ""
    required: false
    type: string
    default: ""
  'my-custom-input-boolean':
    description: ""
    required: false
    type: boolean
    default: true
  'my-custom-input-choice':
    description: ""
    required: true
    type: choice
    default: 'option-1'
    options:
      - 'option-1'
      - 'option-2'

outputs:
  'my-custom-output-string':
    description: ""
    value: ${{ steps['my-step-id'].outputs['my-step-output-name'] }}
  'outputs-can-only-ever-be-strings':
    description: ""
    value: ${{ steps['my-step-id'].outputs['my-step-output-name-2'] }}

runs:
  using: composite
  steps:
    - id: my-step-id
      name: "Friendly Name"
      uses: 'actions/github-script@main'
      with:
        'script': |
          const script = require(`${process.env.GITHUB_ACTION_PATH}/action.js`)
          await script({github, context, core, glob, io, exec, require})
      env:
        'INPUT_MY-INPUT-NAME':   ${{ inputs['my-input-name'] }}
