name: Test-1 Workflow Name

on:
  push:
    branches:
    - playground
    paths:
    - .github/workflows/test-1.yml
  workflow_dispatch:

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@HEAD
      with:
        script: |
          async function printWithJq( obj ) {
            let {stdout, stderr} = { '', ''}
            const options = {
              listeners: {
                stdout: (data) => { stdout += data.toString() },
                stderr: (data) => { stderr += data.toString() },
              }
            }
            await exec.exec('echo', [JSON.stringify(obj), '|', 'jq', '-C', '.'], options)
            console.log('StdOut:', stdout)
            console.log('StdErr:', stderr)
            // return { stdout, stderr }
          }
          await printWithJq( { context } )
          await printWithJq( { env: process.env } )

          core.setOutput("script-1-output", "script-1-output-value")

    - uses: actions/github-script@HEAD
      with:
        script: |
          console.debug({context})
          console.debug({env: process.env})
